packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'components/**'
  - 'libs/**'
  - 'tools/**'

  # exclude packages that are inside test directories
  - '!**/test/**'
